# Generated by Django 5.2 on 2025-04-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_rand'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
