# Generated by Django 5.2 on 2025-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_ocatid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
        migrations.AlterField(
            model_name='news',
            name='ocatid',
            field=models.IntegerField(default=0),
        ),
    ]
