# Generated by Django 5.2 on 2025-04-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
        ('news', '0009_remove_news_pic_alter_news_ocatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ocatid',
            field=models.ForeignKey(blank=True, db_column='ocatid', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.cat', verbose_name='Category'),
        ),
    ]
