# Generated by Django 5.2 on 2025-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picurl',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
