# Generated by Django 5.2 on 2025-05-04 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='act',
            field=models.BooleanField(choices=[(True, 'Publish'), (False, 'Unpublish')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_txt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='rand',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_txt',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
