# Generated by Django 5.2 on 2025-05-06 08:23

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_act_alter_news_body_txt_alter_news_rand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_txt',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_txt',
            field=django_quill.fields.QuillField(),
        ),
    ]
