# Generated by Django 5.2 on 2025-05-06 08:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_body_txt_alter_news_short_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_txt',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_txt',
            field=tinymce.models.HTMLField(),
        ),
    ]
