# Generated by Django 5.2 on 2025-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_main_abouttxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='adname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='adname2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='adurl1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='adurl2',
            field=models.TextField(default=''),
        ),
    ]
